package com.hexu.ebank.user.mapper;

import com.hexu.ebank.user.entity.TUser;
import java.util.List;

public interface TUserMapper {


    /**
     * 根据用户名和密码查询用户
     * @param record
     * @return
     */
    TUser selectByUsernameAndPassWord(TUser record);

    /**
     * select by username
     * @param username
     * @return
     */
    TUser selectByUsername(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Dec 28 16:40:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Dec 28 16:40:16 CST 2019
     */
    int insert(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Dec 28 16:40:16 CST 2019
     */
    TUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Dec 28 16:40:16 CST 2019
     */
    List<TUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Dec 28 16:40:16 CST 2019
     */
    int updateByPrimaryKey(TUser record);
}