package com.hexu.ebank.user.mapper;

import com.hexu.ebank.user.entity.TUserLog;
import java.util.List;

public interface TUserLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbg.generated Sat Dec 28 17:31:02 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbg.generated Sat Dec 28 17:31:02 CST 2019
     */
    int insert(TUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbg.generated Sat Dec 28 17:31:02 CST 2019
     */
    TUserLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbg.generated Sat Dec 28 17:31:02 CST 2019
     */
    List<TUserLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbg.generated Sat Dec 28 17:31:02 CST 2019
     */
    int updateByPrimaryKey(TUserLog record);
}