package com.hexu.ebank.card.entity.warpper;

import com.hexu.ebank.card.entity.TAmount;
import lombok.Data;

@Data
public class TAmountWarpper extends TAmount{

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_currency.currency_name
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    private String currencyName;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_amount_type.amount_type_name
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    private String amountTypeName;

}
