package com.hexu.ebank.user.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.util.Date;


@Data
public class TUserLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_log.id
     *
     * @mbg.generated Sat Dec 28 17:31:02 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_log.username
     *
     * @mbg.generated Sat Dec 28 17:31:02 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_log.opt_time
     *
     * @mbg.generated Sat Dec 28 17:31:02 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date optTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_log.session_id
     *
     * @mbg.generated Sat Dec 28 17:31:02 CST 2019
     */
    private String sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_log.ip
     *
     * @mbg.generated Sat Dec 28 17:31:02 CST 2019
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_log.action
     *
     * @mbg.generated Sat Dec 28 17:31:02 CST 2019
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_log.method
     *
     * @mbg.generated Sat Dec 28 17:31:02 CST 2019
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_log.create_time
     *
     * @mbg.generated Sat Dec 28 17:31:02 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

}