package com.hexu.ebank.card.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class TCard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.id
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.card_no
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.user_id
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.card_type_code
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    private Integer cardTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.product_code
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    private Integer productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.pin_no
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    private String pinNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.cvv2
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    private String cvv2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.status
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.exprie_time
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date exprieTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.create_time
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.update_time
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.id
     *
     * @return the value of t_card.id
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.id
     *
     * @param id the value for t_card.id
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.card_no
     *
     * @return the value of t_card.card_no
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.card_no
     *
     * @param cardNo the value for t_card.card_no
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.user_id
     *
     * @return the value of t_card.user_id
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.user_id
     *
     * @param userId the value for t_card.user_id
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.card_type_code
     *
     * @return the value of t_card.card_type_code
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public Integer getCardTypeCode() {
        return cardTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.card_type_code
     *
     * @param cardTypeCode the value for t_card.card_type_code
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public void setCardTypeCode(Integer cardTypeCode) {
        this.cardTypeCode = cardTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.product_code
     *
     * @return the value of t_card.product_code
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public Integer getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.product_code
     *
     * @param productCode the value for t_card.product_code
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public void setProductCode(Integer productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.pin_no
     *
     * @return the value of t_card.pin_no
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public String getPinNo() {
        return pinNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.pin_no
     *
     * @param pinNo the value for t_card.pin_no
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public void setPinNo(String pinNo) {
        this.pinNo = pinNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.cvv2
     *
     * @return the value of t_card.cvv2
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public String getCvv2() {
        return cvv2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.cvv2
     *
     * @param cvv2 the value for t_card.cvv2
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public void setCvv2(String cvv2) {
        this.cvv2 = cvv2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.status
     *
     * @return the value of t_card.status
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.status
     *
     * @param status the value for t_card.status
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.exprie_time
     *
     * @return the value of t_card.exprie_time
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public Date getExprieTime() {
        return exprieTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.exprie_time
     *
     * @param exprieTime the value for t_card.exprie_time
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public void setExprieTime(Date exprieTime) {
        this.exprieTime = exprieTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.create_time
     *
     * @return the value of t_card.create_time
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.create_time
     *
     * @param createTime the value for t_card.create_time
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.update_time
     *
     * @return the value of t_card.update_time
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.update_time
     *
     * @param updateTime the value for t_card.update_time
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}