package com.hexu.ebank.card.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class TCurrency {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_currency.id
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_currency.currency_name
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    private String currencyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_currency.create_time
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_currency.update_time
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currency.id
     *
     * @return the value of t_currency.id
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currency.id
     *
     * @param id the value for t_currency.id
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currency.currency_name
     *
     * @return the value of t_currency.currency_name
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public String getCurrencyName() {
        return currencyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currency.currency_name
     *
     * @param currencyName the value for t_currency.currency_name
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public void setCurrencyName(String currencyName) {
        this.currencyName = currencyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currency.create_time
     *
     * @return the value of t_currency.create_time
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currency.create_time
     *
     * @param createTime the value for t_currency.create_time
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_currency.update_time
     *
     * @return the value of t_currency.update_time
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_currency.update_time
     *
     * @param updateTime the value for t_currency.update_time
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}