package com.hexu.ebank.user.service;

import com.hexu.ebank.user.entity.TUser;

import java.util.List;

/**
 * User service
 */
public interface TUserService{


    /**
     * login
     * @param tUser
     * @return
     */
    TUser login(TUser tUser);



    /**
     * select by username
     * @param username
     * @return
     */
    TUser selectByUsername(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Dec 28 16:40:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Dec 28 16:40:16 CST 2019
     */
    int insert(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Dec 28 16:40:16 CST 2019
     */
    TUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Dec 28 16:40:16 CST 2019
     */
    List<TUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Sat Dec 28 16:40:16 CST 2019
     */
    int updateByPrimaryKey(TUser record);

}
