package com.hexu.ebank.card.mapper;

import com.hexu.ebank.card.entity.TAmountType;
import java.util.List;

public interface TAmountTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_amount_type
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_amount_type
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    int insert(TAmountType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_amount_type
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    TAmountType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_amount_type
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    List<TAmountType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_amount_type
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    int updateByPrimaryKey(TAmountType record);
}