package com.hexu.ebank.card.mapper;

import com.hexu.ebank.card.entity.TAmount;
import com.hexu.ebank.card.entity.warpper.TAmountWarpper;

import java.util.List;

public interface TAmountMapper {


    List<TAmountWarpper> selectAllTamountWarpper();

    List<TAmountWarpper> selectTamountWarpperByCardId(Integer cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_amount
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_amount
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    int insert(TAmount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_amount
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    TAmount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_amount
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    List<TAmount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_amount
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    int updateByPrimaryKey(TAmount record);
}