package com.hexu.ebank.card.mapper;

import com.hexu.ebank.card.entity.TCard;
import com.hexu.ebank.card.entity.warpper.TCardWarpper;

import java.util.List;

public interface TCardMapper {

    /**
     * select all TCardWarpper
     * @return
     */
    List<TCardWarpper> selectAllTCardWarpper();

    /**
     * select all TCardWarpper by userId
     * @param userId
     * @return
     */
    List<TCardWarpper> selectAllTCardWarpperByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    int insert(TCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    TCard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    List<TCard> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    int updateByPrimaryKey(TCard record);

    TCardWarpper getCardDetailsByCardId(Integer cardId);
}