package com.hexu.ebank.card.mapper;

import com.hexu.ebank.card.entity.TCardType;
import java.util.List;

public interface TCardTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_type
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_type
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    int insert(TCardType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_type
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    TCardType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_type
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    List<TCardType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card_type
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    int updateByPrimaryKey(TCardType record);
}