package com.hexu.ebank.card.mapper;

import com.hexu.ebank.card.entity.TCurrency;
import java.util.List;

public interface TCurrencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_currency
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_currency
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    int insert(TCurrency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_currency
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    TCurrency selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_currency
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    List<TCurrency> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_currency
     *
     * @mbg.generated Sat Dec 28 23:19:59 CST 2019
     */
    int updateByPrimaryKey(TCurrency record);
}